name: ğŸ ğŸ“¦ â‡¢  PyPI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' 

jobs:
  check-and-correct-version:
    name: ğŸ” version number ğŸ”
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Get the version tag
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Check version number and update if necessary
      run: python .github/scripts/version.py ${{ secrets.symfembot_github_token }} ${{ steps.get_version.outputs.VERSION }}

  build-n-publish:
    name: Build and publish ğŸ ğŸ“¦ to PyPI
    needs: check-and-correct-version
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build a binary wheel and a source tarball
      run: |
        pip install wheel
        python setup.py bdist_wheel
        python setup.py sdist --formats=gztar
    - name: Publish ğŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
